name: Branch Quality Gate (Client Only)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches-ignore: [main, master]
    
permissions:
  contents: read
  pull-requests: write
  issues: write
  
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      # שלב 1 – משיכת הקוד מה־repo
      - uses: actions/checkout@v4

      # שלב 2 – התקנת Node.js בגירסה 20
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # שלב 3 – התקנת כל התלויות
      - name: Install dependencies
        run: npm ci

      # שלב 4 – הרצת Unit Tests עם Headless Chrome
      - name: Run Unit Tests
        run: echo "Skipping FE tests for now"

      # שלב 5 – Build בפרופיל Production
      - name: Build Angular App
        run: npm run build -- --configuration=production-ci

  summary:
    runs-on: ubuntu-latest
    needs: [frontend]
    if: always()
    steps:
      - id: compose
        run: |
          FRONT="${{ needs.frontend.result }}"
          if [ "$FRONT" = "success" ]; then
            echo "status=ok" >> $GITHUB_OUTPUT
            echo "message=✅ הבראנץ' תקין" >> $GITHUB_OUTPUT
          else
            echo "status=fail" >> $GITHUB_OUTPUT
            echo "message=❌ הבראנץ' לא תקין – ראו לוגים ב-Actions (frontend=$FRONT)" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/github-script@v7
        with:
          script: |
            const body = `${{ steps.compose.outputs.message }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
