name: Branch Quality Gate (Client Only)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches-ignore: [main, master]

# מניעת ריצות כפולות על אותו ref
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  DIST_DIR: dist/studio-project/browser  
  PORT: 4200
  CI: "true"
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Cache Angular build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/angular
          key: angular-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            angular-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Build (production-ci)
        run: npm run build -- --configuration=production-ci
   
      - name: Verify dist exists
        run: |
          test -d "$DIST_DIR" || (echo "❌ $DIST_DIR not found" && exit 1)
          test -f "$DIST_DIR/index.html" || (echo "❌ index.html missing under $DIST_DIR" && exit 1)


      - name: Smoke Test
        run: |
          npx http-server "$DIST_DIR" -p "$PORT" -s &
          SERVER_PID=$!

          for i in {1..10}; do
            if curl -fsS "http://localhost:${PORT}" > /tmp/page.html; then
              break
            fi
            sleep 1
          done

          if [ ! -s /tmp/page.html ]; then
            echo "❌ Server did not respond on time."
            kill $SERVER_PID || true
            exit 1
          fi

          if ! grep -q "<app-root" /tmp/page.html; then
            echo "❌ <app-root> not found in served HTML."
            kill $SERVER_PID || true
            exit 1
          fi

          kill $SERVER_PID || true

      - name: Upload build artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dist-on-failure
          path: ${{ env.DIST_DIR }}
          if-no-files-found: ignore

  summary:
    runs-on: ubuntu-latest
    needs: [frontend]
    if: always()
    steps:
      - id: compose
        run: |
          FRONT="${{ needs.frontend.result }}"
          if [ "$FRONT" = "success" ]; then
            echo "message=✅ הבראנץ' תקין" >> $GITHUB_OUTPUT
          else
            echo "message=❌ הבראנץ' לא תקין – ראו לוגים ב-Actions (frontend=$FRONT)" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR (same-repo only)
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/github-script@v7
        with:
          script: |
            const body = `${{ steps.compose.outputs.message }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
